### ISSUE TITLE
[BUILD FAILED] reinstall grpc

### ISSUE THREAD

**Issue by khanhduy62** [facebook/homebrew-fb#60] opened 2021-05-30 12:35 UTC
I have got this error in file 01.idb_build.sh after I reinstall grpc `brew reinstall grpc`

```
CompileC /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBStorageManager.o /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Utility/FBIDBStorageManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'idb_companion' from project 'idb_companion')
    cd /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2
    export LANG\=en_US.US-ASCII
    clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Index/DataStore -iquote /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-generated-files.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-own-target-headers.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/all-product-headers.yaml -iquote /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-project-headers.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug/include -I/usr/local/include -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources-normal/x86_64 -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources/x86_64 -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources -F/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug -MMD -MT dependencies -MF /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBStorageManager.d --serialize-diagnostics /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBStorageManager.dia -c /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Utility/FBIDBStorageManager.m -o /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBStorageManager.o

CompileC /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBServiceHandler.o /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBServiceHandler.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'idb_companion' from project 'idb_companion')
    cd /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2
    export LANG\=en_US.US-ASCII
    clang -x objective-c++ -target x86_64-apple-macos10.14 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu++14 -stdlib\=libc++ -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path\=/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -index-store-path /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Index/DataStore -iquote /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-generated-files.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-own-target-headers.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-all-non-framework-target-headers.hmap -ivfsoverlay /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/all-product-headers.yaml -iquote /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/idb_companion-project-headers.hmap -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug/include -I/usr/local/include -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources-normal/x86_64 -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources/x86_64 -I/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/DerivedSources -F/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug -MMD -MT dependencies -MF /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBServiceHandler.d --serialize-diagnostics /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBServiceHandler.dia -c /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBServiceHandler.mm -o /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Intermediates.noindex/idb_companion.build/Debug/idb_companion.build/Objects-normal/x86_64/FBIDBServiceHandler.o
In file included from /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBServiceHandler.mm:16:
/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBCommandExecutor.h:173:9: warning: parameter 'legacyFormat' not found in the function declaration [-Wdocumentation]
 @param legacyFormat YES if the legacy format should be used, NO otherwise.
        ^~~~~~~~~~~~
/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBCommandExecutor.h:173:9: note: did you mean 'nestedFormat'?
 @param legacyFormat YES if the legacy format should be used, NO otherwise.
        ^~~~~~~~~~~~
        nestedFormat
/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBServiceHandler.mm:100:14: error: no matching member function for call to 'set_data'
    payload->set_data(buffer, size);
    ~~~~~~~~~^~~~~~~~
In file included from /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/idb_companion/Server/FBIDBServiceHandler.mm:10:
In file included from /tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug/idbGRPC/idb.grpc.pb.h:14:
/tmp/idb-companion-20210530-19270-1drj5ib/idb-1.1.2/build/Build/Products/Debug/idbGRPC/idb.pb.h:21366:22: note: candidate template ignored: substitution failure: variably modified type 'unsigned long (&)[BufferOutputSize]' cannot be used as a template argument
inline void Payload::set_data(ArgT0&& arg0, ArgT... args) {
                     ^
1 warning and 1 error generated.
```

**Comment by KapJI** [comment] 2021-06-01 09:32
Duplicate of #59

**Closed by KapJI** 2021-06-01 09:32 UTC
