### ISSUE TITLE
arpa/inet.h file not found issue

### ISSUE THREAD

**Issue by danoz73** [facebook/homebrew-fb#2] opened 2015-10-06 08:04 UTC
I am trying to install buck using Homebrew:

```shell
brew install --HEAD buck
```

I get the following error in the `ant` portion of the process:

```shell
==> ant
Last 15 lines from /Users/D/Library/Logs/Homebrew/buck/01.ant:
    [javac] Compiling 17 source files to /private/tmp/buck20151006-3743-uvhmqb/build/classes
    [javac] Compiling 1242 source files to /private/tmp/buck20151006-3743-uvhmqb/build/classes
    [javac] [compiled 201561 lines in 7494 ms: 26896.3 lines/s]
    [javac] [2403 .class files generated]

client:
     [exec] third-party/nailgun/nailgun-client/ng.c:26:11: fatal error: 'arpa/inet.h' file not found
     [exec]         #include <arpa/inet.h>
     [exec]                  ^
     [exec] 1 error generated.

BUILD FAILED
/private/tmp/buck20151006-3743-uvhmqb/build.xml:984: exec returned: 1
```

Homebrew says my current version of ant is `ant 1.9.6`

**Comment by Coneko** [comment] 2015-10-07 17:51
Did you install Xcode or the Developer Command Line Tools?

I think you need them to install brew, but you might have uninstalled them.

**Comment by Coneko** [comment] 2015-10-07 17:53
Going to close it as duplicate of buck#450 in the meantime, let's continue the discussion there.

**Closed by Coneko** 2015-10-07 17:53 UTC
